language: node_js

stages:
  - lint

node_js:
  - "10"

cache:
  #  yarn: true
  directories:
    - node_modules

jobs:
  include:
    # ESLint
    - stage: "lint"
      name: "ESLint"
      install:
        - |
          npm install eslint \
          eslint-plugin-vue
      script:
#        - node_modules/eslint/bin/eslint.js docs/.vuepress/
        - npx eslint ./docs/.vuepress/ --ext vue,js
